spring.application.name=notification
server.servlet.context-path=/api/v1/notification
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=alerts
spring.datasource.username=postgres
spring.datasource.password=${POSTGRES_PASSWORD}

spring.flyway.schemas=alerts
spring.flyway.default-schema=alerts
spring.flyway.create-schemas=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=alerts

spring.config.import=optional:file:./config/telegramDetails.yml
